### ISSUE TITLE
Create UML for ImplicitPIC

### ISSUE THREAD

**Issue by tyjoto** [tyjoto/plasma#10]

**Comment by tyjoto** [comment]
Needed for structure uml diagram

**Things to Do**
- [x] add ImplicitPIC class
- [x] add other classes

**Done When**
- [x] uploaded here
- [x] approved by @cdtho

**Comment by tyjoto** [comment]
![ImplicitPIC](https://user-images.githubusercontent.com/45111310/144653004-c677517f-9d9d-461f-bb9c-16ba1316dc23.png)

**Comment by cdtho** [comment]
Same comment as before... I think you misspelled Class : NodeFieldData. Looks good otherwise!

**Comment by tyjoto** [comment]
fixed spelling and change two classes to abstract classes

![ImplicitPIC](https://user-images.githubusercontent.com/45111310/144684067-e065aace-5e63-4ec4-932f-61e45c6f137f.png)
