### ISSUE TITLE
Create UML for PlasmaData

### ISSUE THREAD

**Issue by tyjoto** [tyjoto/plasma#5]
Creation of class structure of PlasmaData for UML structure documentation

**Things to Do**
- [x]  Add Attributes
- [x]  Add Methods

**Completed When**
- [x] Uploaded UML Documentation here to this issue
- [x] Reviewed and approved by @cdtho

**Comment by tyjoto** [comment]
Updated 12/3/2021: (added note in separate box and cleaned up spacing for easier readability)
Updated 12/3/2021(later): (added other classes)

![PlasmaData](https://user-images.githubusercontent.com/45111310/144693311-c0f01a67-180f-4211-a3a9-e3d1bc1d2d84.png)

**Comment by cdtho** [comment]
Looks pretty good! Seems like you got everything important
