### ISSUE TITLE
Create UML for OutputCtrl

### ISSUE THREAD

**Issue by tyjoto** [tyjoto/plasma#9]

**Comment by tyjoto** [comment]
Need to create class structure for OutputCtrl

**Things to Do**
- [x] add outside classes
- [x] add OutputCtrl class methods and attributes

**Done When**
- [x] uploaded here
- [x] approved by @cdtho

**Comment by tyjoto** [comment]
![OutputCtrl](https://user-images.githubusercontent.com/45111310/143493187-11ac0283-2666-4f3c-89c6-acf74873ac1f.png)

**Comment by cdtho** [comment]
I think you misspelled Class : NodeFieldData

**Comment by cdtho** [comment]
Looks good though!

**Comment by tyjoto** [comment]
Fixed spelling

![OutputCtrl](https://user-images.githubusercontent.com/45111310/144684019-939e2eae-845d-4f9f-87a0-5f6425898f8b.png)
